# Generated by Django 4.1.4 on 2023-03-17 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.CharField(max_length=20)),
                ('link', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
            ],
        ),
    ]
